### ISSUE TITLE
pop up

### ISSUE THREAD

**Issue by andgarzonmal** [wandergithub/Portfolio#12]
![StandingOvationGIF](https://user-images.githubusercontent.com/95243996/162220257-000fa280-25e4-4d98-8206-bcb3a249c4db.gif)
congratulations, your work is aweasome ples take a look to  this suggestions

- [x]  link your images usin the ./ notation

**Comment by wandergithub** [comment]
Solved!
Images are working now. Thanks for your suggestions @andgarzonmal 😄.
