### ISSUE TITLE
Observations to improve your proyect

### ISSUE THREAD

**Issue by AxelSoler** [wandergithub/Portfolio#5]
Kindly try to make the following parts of the website more responsive to the screen width when the screen is higher than 768px:
1. Social media icons
2. Pictures inside work section
3. Title from the work section

**Comment by wandergithub** [comment]
Hi @AxelSoler, thanks a lot for your suggestions. I invite you to check the [PR](https://github.com/wandergithub/Portfolio/pull/18) where I [addressed](https://github.com/wandergithub/Portfolio/pull/18/commits/9efa31e0561e8ad22b19c11d40aeb4881cb3b485) them and solve the 3 issues if you are interested.
