### ISSUE TITLE
Navigation Hover

### ISSUE THREAD

**Issue by Adanzeakonobi** [wandergithub/Portfolio#8]
- The hover effect on the Navigation section should be applied to the icons individually.
- Kindly use percentage width on CSS styling for responsive web design instead of fixed width.

**Comment by wandergithub** [comment]
Thanks for your suggestions @Adanzeakonobi they were very useful. I improved the hover effects and solve all width problems to make the web responsive. You can check out the [PR](https://github.com/wandergithub/Portfolio/pull/18) if you are interested.
